# Generated by Django 2.2 on 2020-08-21 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=30)),
                ('prenom', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('date_naiss', models.DateField()),
                ('tel', models.CharField(default='', max_length=8, unique=True)),
                ('disp', models.FloatField(verbose_name=(0, 1, 2, 3, 4, 5))),
                ('exp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cv', models.FileField(upload_to='')),
                ('msg', models.CharField(max_length=300)),
                ('cand_status', models.CharField(choices=[('New Candidate', 'new'), ('In Progress', 'progress'), ('Accepted', 'accepted'), ('Refused', 'refused')], default='New Candidate', max_length=2)),
                ('email_status', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=2)),
            ],
        ),
    ]
