# Generated by Django 2.2 on 2020-08-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='cand_status',
            field=models.CharField(choices=[('New Candidate', 'new'), ('In Progress', 'progress'), ('Accepted', 'accepted'), ('Refused', 'refused')], default='New Candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='disp',
            field=models.FloatField(verbose_name=(0, 1, 2, 3, 4, 5)),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email_status',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=20),
        ),
    ]
