# Generated by Django 2.2 on 2020-08-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20200821_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='cv',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='disp',
            field=models.FloatField(verbose_name=(0, 1, 2, 3, 4, 5)),
        ),
    ]
