# Generated by Django 2.2 on 2020-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20200822_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='cv',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='disp',
            field=models.FloatField(verbose_name=(0, 1, 2, 3, 4, 5)),
        ),
    ]
